[profile.default]
src = "src"
out = "out"
libs = ["/Users/aditya/Developer/MOnad/Monad/axiom/node_modules", "lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"
]
